# Generated by Django 6.0.3 on 2026-03-31 11:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoBiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.IntegerField(choices=[(0, 'Prefiero No Decir'), (1, 'Hombre'), (2, 'Mujer')])),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_de_sangre', models.IntegerField(choices=[(0, 'A Positivo'), (1, 'A Negativo'), (2, 'B Positivo'), (3, 'B Negativo'), (4, 'Ab Positivo'), (5, 'Ab Negativo'), (6, 'O Positivo'), (7, 'O Negativo')], db_index=True)),
                ('enfermedades', models.TextField(blank=True, db_index=True, max_length=300, null=True)),
                ('alergias', models.TextField(blank=True, db_index=True, max_length=300, null=True)),
                ('nss', models.CharField(blank=True, db_index=True, max_length=11, null=True)),
                ('poliza_seguro', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('aseguradora', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('grupo_biker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miApp.grupobiker')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('relacion', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('tipo_vehiculo', models.IntegerField(choices=[(0, 'Deportiva'), (1, 'Touring'), (2, 'Crucero'), (3, 'Enduro'), (4, 'Scooter'), (5, 'Naked'), (6, 'Chopper'), (7, 'Otro')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(0, 'No iniciado'), (1, 'En curso'), (2, 'Finalizado'), (3, 'Pausado'), (4, 'Cancelado')], default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('lugar_de_inicio', models.CharField(max_length=200)),
                ('lugar_de_fin', models.CharField(blank=True, max_length=200, null=True)),
                ('distancia_estimada', models.FloatField(blank=True, null=True)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaje', to='miApp.vehiculo')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
