# Generated by Django 6.0.3 on 2026-04-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_remove_usuario_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
