# Generated by Django 6.0.3 on 2026-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_usuario_managers_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Prefiero No Decir'), (1, 'Hombre'), (2, 'Mujer')], default=0),
        ),
    ]
