# Generated by Django 6.0.3 on 2026-04-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_alter_usuario_fecha_nacimiento_alter_usuario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_sangre',
            field=models.IntegerField(blank=True, choices=[(0, 'A Positivo'), (1, 'A Negativo'), (2, 'B Positivo'), (3, 'B Negativo'), (4, 'Ab Positivo'), (5, 'Ab Negativo'), (6, 'O Positivo'), (7, 'O Negativo')], null=True),
        ),
    ]
