# Generated by Django 6.0.3 on 2026-04-03 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0005_alter_usuario_tipo_de_sangre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto_emergencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='miApp.vehiculo'),
        ),
        migrations.CreateModel(
            name='UsuarioVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.vehiculo')),
            ],
            options={
                'unique_together': {('usuario', 'vehiculo')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='miApp.UsuarioVehiculo', to='miApp.vehiculo'),
        ),
    ]
