# Generated by Django 6.0.3 on 2026-04-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0006_remove_vehiculo_usuario_vehiculo_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='activo',
        ),
    ]
