# Generated by Django 6.0.3 on 2026-04-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0007_remove_vehiculo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='vehiculo',
        ),
    ]
