# Generated by Django 6.0.3 on 2026-05-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0008_remove_viaje_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupobiker',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(0, 'Miembro'), (1, 'Líder')], default=0),
        ),
    ]
