# Generated by Django 6.0.3 on 2026-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0009_grupobiker_lider_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupobiker',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='grupos/'),
        ),
    ]
